# Generated by Django 5.2.8 on 2025-11-13 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(choices=[('pcs', 'Pieces'), ('ml', 'Milliliters')], default='pcs', help_text='Unit of measurement (e.g. ml, pcs)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('purchase_quantity', models.IntegerField(default=0)),
                ('sale_quantity', models.IntegerField(default=0)),
                ('opening_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocktype')),
            ],
        ),
    ]
