# Generated by Django 5.2.8 on 2025-11-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
