# Generated by Django 5.2.8 on 2025-12-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebill',
            name='bill_number',
            field=models.CharField(default='TEMPBILL', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
