# Generated by Django 5.2.8 on 2025-11-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_customer_salebill_bill_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
