# Generated by Django 5.2.8 on 2025-11-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('sale', '0003_alter_productsale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
